// Concord TrackSync - Daily Output Report PDF generator (server-side only).
//
// Builds a professional, print-ready PDF for the Daily Output Report using
// pdfkit. This module is server-only (depends on pdfkit which requires `fs`)
// and must NOT be imported by client components.

import PDFDocument from 'pdfkit';
import { STANDARD_SIZES } from './reportsService.js';

const COMPANY_NAME = 'Concord Footwear (Pvt) Ltd';
const REPORT_TITLE = 'Daily Output Report';
const SYSTEM_FOOTER = 'Generated by Concord TrackSync';

/** Format a cell value: 0, null, undefined -> "-", otherwise the number. */
function fmt(value) {
  if (value === null || value === undefined || value === 0) return '-';
  return String(value);
}

/**
 * Build a professional PDF buffer for the Daily Output Report.
 *
 * @param {object} matrixData  output of fetchDailyOutputReport / aggregateDailyOutput
 * @param {object} [filters]   { departmentId, date, recordStatus, qcStatus }
 * @returns {Promise<{ buffer: Buffer, fileName: string }>}
 */
export async function buildDailyOutputPdf(matrixData, filters = {}) {
  const {
    date,
    departmentId = 'All Departments',
    recordStatus = 'ALL',
    qcStatus = 'ALL',
  } = filters;

  const sizeList = (matrixData && matrixData.sizes) || STANDARD_SIZES;
  const rows = (matrixData && matrixData.rows) || [];
  const summary =
    (matrixData && matrixData.summary) ||
    { sizes: {}, dailyTotal: 0, cumulativeOutput: 0 };

  const doc = new PDFDocument({ size: 'A4', margin: 40, layout: 'landscape', compress: false });

  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  doc.on('end', () => {});

  // ---- Header ----
  doc.fontSize(16).font('Helvetica-Bold').text(COMPANY_NAME, { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(12).font('Helvetica').text(REPORT_TITLE, { align: 'center' });
  doc.moveDown(0.3);

  // ---- Active filters banner ----
  doc.fontSize(9).font('Helvetica');
  const filterLine = [
    `Date: ${date || '-'}`,
    `Department: ${departmentId}`,
    `Record Status: ${recordStatus}`,
    `QC Status: ${qcStatus}`,
  ].join('    |    ');
  doc.text(filterLine, { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(doc.x, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.5);

  // ---- Table ----
  const tableLeft = doc.page.margins.left;
  const tableRight = doc.page.width - doc.page.margins.right;
  const tableWidth = tableLeft - tableRight;
  const colWidths = { po: 90, size: 32, dailyTotal: 60, cumulative: 70 };
  const sizeColWidth = colWidths.size;

  const headers = ['PO Number', ...sizeList, 'Daily Total', 'Cumulative Output'];
  const allWidths = [
    colWidths.po,
    ...sizeList.map(() => sizeColWidth),
    colWidths.dailyTotal,
    colWidths.cumulative,
  ];

  const drawTableRow = (cells, opts = {}) => {
    const { bold = false, fill = null } = opts;
    const startX = tableLeft;
    const y = doc.y;
    const rowHeight = 18;
    if (fill) doc.rect(startX, y, tableWidth, rowHeight).fill(fill);
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
    let x = startX;
    cells.forEach((cell, i) => {
      const w = allWidths[i];
      const isFirst = i === 0;
      doc.fillColor('black').text(String(cell), x + (isFirst ? 4 : 2), y + 4, {
        width: w - 4,
        align: isFirst ? 'left' : 'center',
        lineBreak: false,
        ellipsis: true,
      });
      x += w;
    });
    doc.y = y + rowHeight;
    doc.moveTo(startX, doc.y).lineTo(startX + tableWidth, doc.y).strokeColor('#cccccc').stroke();
  };

  // Header row.
  drawTableRow(headers, { bold: true, fill: '#1f2937' });
  doc.fillColor('white');
  let hx = tableLeft;
  const hdrY = doc.y - 18;
  doc.font('Helvetica-Bold').fontSize(8);
  headers.forEach((h, i) => {
    const w = allWidths[i];
    doc.text(h, hx + (i === 0 ? 4 : 2), hdrY + 4, {
      width: w - 4,
      align: i === 0 ? 'left' : 'center',
      lineBreak: false,
    });
    hx += w;
  });
  doc.fillColor('black');

  // Data rows.
  rows.forEach((row) => {
    const cells = [
      row.po,
      ...sizeList.map((s) => fmt(row.sizes[s])),
      fmt(row.dailyTotal),
      fmt(row.cumulativeOutput),
    ];
    drawTableRow(cells);
  });

  // Summary footer row.
  const summaryCells = [
    'TOTAL',
    ...sizeList.map((s) => fmt(summary.sizes[s])),
    fmt(summary.dailyTotal),
    fmt(summary.cumulativeOutput),
  ];
  const beforeSummaryY = doc.y;
  drawTableRow(summaryCells, { bold: true, fill: '#e5e7eb' });
  let sx = tableLeft;
  doc.font('Helvetica-Bold').fontSize(8);
  summaryCells.forEach((c, i) => {
    const w = allWidths[i];
    doc.text(String(c), sx + (i === 0 ? 4 : 2), beforeSummaryY + 4, {
      width: w - 4,
      align: i === 0 ? 'left' : 'center',
      lineBreak: false,
    });
    sx += w;
  });
  doc.fillColor('black');
  doc.moveDown(1);

  // ---- Signature section ----
  doc.fontSize(10).font('Helvetica');
  const sigY = doc.y;
  const sigWidth = 250;
  doc.text('Prepared By: ___________________', tableLeft, sigY);
  doc.text('Approved By: ___________________', tableLeft + sigWidth + 30, sigY);
  doc.moveDown(2);

  // ---- System footer ----
  doc.fontSize(8).font('Helvetica-Oblique').text(SYSTEM_FOOTER, { align: 'center' });
  doc.end();

  const awaitBuffer = () =>
    new Promise((resolve) => {
      if (doc._ended) return resolve(Buffer.concat(chunks));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

  const buffer = await awaitBuffer();
  const fileName = `Daily_Output_Report_${date || new Date().toISOString().slice(0, 10)}.pdf`;
  return { buffer, fileName };
}