// Concord TrackSync - Daily Output Report PDF generator (server-side only).
//
// Builds a professional, print-ready PDF for the Daily Output Report using
// pdfkit. This module is server-only (depends on pdfkit which requires `fs`)
// and must NOT be imported by client components.

import PDFDocument from 'pdfkit';
import { STANDARD_SIZES } from './reportsService.js';

const COMPANY_NAME = 'Concord Footwear (Pvt) Ltd';
const REPORT_TITLE = 'Daily Output Report';
const SYSTEM_FOOTER = 'Generated by Concord TrackSync';

/** Format a cell value: 0, null, undefined -> "-", otherwise the number. */
function fmt(value) {
  if (value === null || value === undefined || value === 0) return '-';
  return String(value);
}

/**
 * Build a professional PDF buffer for the Daily Output Report.
 *
 * @param {object} matrixData  output of fetchDailyOutputReport / aggregateDailyOutput
 * @param {object} [filters]   { departmentId, date, recordStatus, qcStatus }
 * @returns {Promise<{ buffer: Buffer, fileName: string }>}
 */
export async function buildDailyOutputPdf(matrixData, filters = {}) {
  const {
    date,
    departmentId = 'All Departments',
    recordStatus = 'ALL',
    qcStatus = 'ALL',
  } = filters;

  const sizeList = (matrixData && matrixData.sizes) || STANDARD_SIZES;
  const rows = (matrixData && matrixData.rows) || [];
  const summary =
    (matrixData && matrixData.summary) ||
    { sizes: {}, dailyTotal: 0, cumulativeOutput: 0 };

  const doc = new PDFDocument({ size: 'A4', margin: 40, layout: 'landscape', compress: false });

  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  doc.on('end', () => {});

  // ---- Header ----
  doc.fontSize(16).font('Helvetica-Bold').text(COMPANY_NAME, { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(12).font('Helvetica').text(REPORT_TITLE, { align: 'center' });
  doc.moveDown(0.3);

  // ---- Active filters banner ----
  doc.fontSize(9).font('Helvetica');
  const filterLine = [
    `Date: ${date || '-'}`,
    `Department: ${departmentId}`,
    `Record Status: ${recordStatus}`,
    `QC Status: ${qcStatus}`,
  ].join('    |    ');
  doc.text(filterLine, { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(doc.x, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.5);

  // ---- Table ----
  const tableLeft = doc.page.margins.left;
  const tableRight = doc.page.width - doc.page.margins.right;
  // Usable width (A4 landscape: ~762pt). Must be right-left, NOT left-right.
  const tableWidth = tableRight - tableLeft;

  // Fixed widths for the label/total columns; the 16 size columns share the
  // remainder so the grid spans the full table width edge-to-edge.
  const fixedWidths = { po: 90, dailyTotal: 60, cumulative: 70 };
  const sizeColWidth =
    (tableWidth - fixedWidths.po - fixedWidths.dailyTotal - fixedWidths.cumulative) /
    sizeList.length;
  const allWidths = [
    fixedWidths.po,
    ...sizeList.map(() => sizeColWidth),
    fixedWidths.dailyTotal,
    fixedWidths.cumulative,
  ];

  // Styling constants: dark header/total bands with bold white text, light
  // gray grid lines for clearly separated rows and columns.
  const GRID_COLOR = '#d1d5db';
  const HEADER_BG = '#1f2937';
  const TOTAL_BG = '#374151';
  const TEXT_DARK = '#111111';
  const TEXT_WHITE = '#ffffff';
  const ROW_HEIGHT = 18;

  // Column boundary x positions (for the vertical grid lines).
  const colXs = [];
  {
    let x = tableLeft;
    for (const w of allWidths) {
      colXs.push(x);
      x += w;
    }
    colXs.push(tableRight);
  }

  /**
   * Draw one table row in a single pass: background fill (if any), cell text
   * in the requested color, then the horizontal grid rule underneath.
   */
  const drawTableRow = (cells, opts = {}) => {
    const { bold = false, fill = null, textColor = TEXT_DARK } = opts;
    const startX = tableLeft;
    const y = doc.y;
    if (fill) {
      doc.rect(startX, y, tableWidth, ROW_HEIGHT).fill(fill);
    }
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
    doc.fillColor(textColor);
    let x = startX;
    cells.forEach((cell, i) => {
      const w = allWidths[i];
      const isFirst = i === 0;
      doc.text(String(cell), x + (isFirst ? 4 : 2), y + 4, {
        width: w - 4,
        align: isFirst ? 'left' : 'center',
        lineBreak: false,
        ellipsis: true,
      });
      x += w;
    });
    doc.y = y + ROW_HEIGHT;
    doc.moveTo(startX, doc.y).lineTo(tableRight, doc.y).stroke();
  };

  doc.lineWidth(0.5);
  doc.strokeColor(GRID_COLOR);

  const tableTopY = doc.y;

  // Header row: dark fill + bold pure-white text (drawn once).
  const headers = ['PO Number', ...sizeList, 'Daily Total', 'Cumulative Output'];
  drawTableRow(headers, { bold: true, fill: HEADER_BG, textColor: TEXT_WHITE });

  // Data rows: black text on the page background.
  rows.forEach((row) => {
    const cells = [
      row.po,
      ...sizeList.map((s) => fmt(row.sizes[s])),
      fmt(row.dailyTotal),
      fmt(row.cumulativeOutput),
    ];
    drawTableRow(cells);
  });

  // Summary footer row: dark fill + bold pure-white text (drawn once).
  const summaryCells = [
    'TOTAL',
    ...sizeList.map((s) => fmt(summary.sizes[s])),
    fmt(summary.dailyTotal),
    fmt(summary.cumulativeOutput),
  ];
  drawTableRow(summaryCells, { bold: true, fill: TOTAL_BG, textColor: TEXT_WHITE });

  const tableBottomY = doc.y;

  // Full grid: top border + a vertical rule at every column boundary so rows
  // and columns are clearly separated.
  doc.moveTo(tableLeft, tableTopY).lineTo(tableRight, tableTopY).stroke();
  colXs.forEach((x) => {
    doc.moveTo(x, tableTopY).lineTo(x, tableBottomY).stroke();
  });

  // Restore dark text so the signature/footer text below the table stays
  // visible (the TOTAL row's last text fill was white).
  doc.fillColor(TEXT_DARK);
  doc.moveDown(1);

  // ---- Signature section ----
  doc.fontSize(10).font('Helvetica');
  const sigY = doc.y;
  const sigWidth = 250;
  doc.text('Prepared By: ___________________', tableLeft, sigY);
  doc.text('Approved By: ___________________', tableLeft + sigWidth + 30, sigY);
  doc.moveDown(2);

  // ---- System footer ----
  doc.fontSize(8).font('Helvetica-Oblique').text(SYSTEM_FOOTER, { align: 'center' });
  doc.end();

  const awaitBuffer = () =>
    new Promise((resolve) => {
      if (doc._ended) return resolve(Buffer.concat(chunks));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

  const buffer = await awaitBuffer();
  const fileName = `Daily_Output_Report_${date || new Date().toISOString().slice(0, 10)}.pdf`;
  return { buffer, fileName };
}