// Concord TrackSync - Daily Output Report PDF generator (server-side only).
//
// Builds a professional, print-ready PDF for the Daily Output Report using
// pdfkit. The grid matches the reference format: under each PO one row per
// selected QC status (ALL = Forward / B Grade / C Grade / Lab Testing /
// Return / Reworked), then a highlighted "Sub Total" row summing the block,
// with the PO's cumulative output on the Cumulative column. Columns run
// PO | Status | 35..50 | Total | Cumulative, and the table paginates with a
// repeated header when it outgrows one page. This module is server-only
// (depends on pdfkit which requires `fs`) and must NOT be imported by
// client components.

import PDFDocument from 'pdfkit';
import { STANDARD_SIZES } from './reportsService.js';

const COMPANY_NAME = 'Concord Footwear (Pvt) Ltd';
const REPORT_TITLE = 'Daily Output Report';
const SYSTEM_FOOTER = 'Generated by Concord TrackSync';

/** Format a cell value: 0, null, undefined -> "-", otherwise the number. */
function fmt(value) {
  if (value === null || value === undefined || value === 0) return '-';
  return String(value);
}

/**
 * Build a professional PDF buffer for the Daily Output Report.
 *
 * Grid structure (matching the reference format): one row per selected QC
 * status under each PO, followed by a highlighted "Sub Total" row per PO
 * block that sums the size quantities and totals across the block's status
 * rows. The Cumulative column carries the PO's cumulative output on its
 * Sub Total row. Columns: PO | Status | 35..50 | Total | Cumulative.
 *
 * @param {object} matrixData  output of fetchDailyOutputReport / aggregateDailyOutput
 * @param {object} [filters]   { departmentId, date, recordStatus, qcStatus, qcStatuses }
 * @returns {Promise<{ buffer: Buffer, fileName: string }>}
 */
export async function buildDailyOutputPdf(matrixData, filters = {}) {
  const {
    date,
    departmentId = 'All Departments',
    recordStatus = 'ALL',
    qcStatus = 'ALL',
    qcStatuses = null,
  } = filters;

  const sizeList = (matrixData && matrixData.sizes) || STANDARD_SIZES;
  const rows = (matrixData && matrixData.rows) || [];
  const summary =
    (matrixData && matrixData.summary) ||
    { sizes: {}, dailyTotal: 0, cumulativeOutput: 0 };

  // Status blocks drive the PO x QC-status grid: one row per selected
  // status + a highlighted Sub Total per PO. A legacy matrix without
  // statusBlocks falls back to a single 'ALL' status row per PO.
  const blocks =
    (matrixData && matrixData.statusBlocks) ||
    rows.map((row) => ({
      po: row.po,
      statuses: [{ status: 'ALL', sizes: row.sizes, total: row.dailyTotal }],
      subTotal: { sizes: row.sizes, total: row.dailyTotal },
      cumulativeOutput: row.cumulativeOutput,
    }));

  // Banner label: the joined multi-select list, or ALL.
  const qcLabel =
    Array.isArray(qcStatuses) && qcStatuses.length > 0
      ? qcStatuses.join(', ')
      : qcStatus || 'ALL';

  const doc = new PDFDocument({ size: 'A4', margin: 40, layout: 'landscape', compress: false });

  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  doc.on('end', () => {});

  // ---- Header ----
  doc.fontSize(16).font('Helvetica-Bold').text(COMPANY_NAME, { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(12).font('Helvetica').text(REPORT_TITLE, { align: 'center' });
  doc.moveDown(0.3);

  // ---- Active filters banner ----
  doc.fontSize(9).font('Helvetica');
  const filterLine = [
    `Date: ${date || '-'}`,
    `Department: ${departmentId}`,
    `Record Status: ${recordStatus}`,
    `QC Status: ${qcLabel}`,
  ].join('    |    ');
  doc.text(filterLine, { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(doc.x, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.5);

  // ---- Table ----
  const tableLeft = doc.page.margins.left;
  const tableRight = doc.page.width - doc.page.margins.right;
  // Usable width (A4 landscape: ~762pt). Must be right-left, NOT left-right.
  const tableWidth = tableRight - tableLeft;

  // Fixed widths for the label/total columns; the 16 size columns share the
  // remainder so the grid spans the full table width edge-to-edge.
  // Column order: PO | Status | 35..50 | Total | Cumulative.
  const fixedWidths = { po: 70, status: 74, total: 55, cumulative: 70 };
  const sizeColWidth =
    (tableWidth -
      fixedWidths.po -
      fixedWidths.status -
      fixedWidths.total -
      fixedWidths.cumulative) /
    sizeList.length;
  const allWidths = [
    fixedWidths.po,
    fixedWidths.status,
    ...sizeList.map(() => sizeColWidth),
    fixedWidths.total,
    fixedWidths.cumulative,
  ];

  // Styling constants: dark header/total bands with bold white text, a
  // highlighted band for every PO's Sub Total row, and crisp pure-black grid
  // lines for clearly separated rows and columns.
  const GRID_COLOR = '#000000';
  const HEADER_BG = '#1f2937';
  const TOTAL_BG = '#374151';
  const SUBTOTAL_BG = '#d1d5db';
  const TEXT_DARK = '#111111';
  const TEXT_WHITE = '#ffffff';
  const ROW_HEIGHT = 18;

  // Column boundary x positions (for the vertical grid lines).
  const colXs = [];
  {
    let x = tableLeft;
    for (const w of allWidths) {
      colXs.push(x);
      x += w;
    }
    colXs.push(tableRight);
  }

  /**
   * Draw one table row in a single pass: background fill (if any), cell text
   * in the requested color, then the horizontal grid rule underneath.
   */
  const drawTableRow = (cells, opts = {}) => {
    const { bold = false, fill = null, textColor = TEXT_DARK } = opts;
    const startX = tableLeft;
    const y = doc.y;
    if (fill) {
      doc.rect(startX, y, tableWidth, ROW_HEIGHT).fill(fill);
    }
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
    doc.fillColor(textColor);
    let x = startX;
    cells.forEach((cell, i) => {
      const w = allWidths[i];
      // PO and Status are left-aligned label columns; sizes/totals center.
      const isLeft = i <= 1;
      doc.text(String(cell), x + (isLeft ? 4 : 2), y + 4, {
        width: w - 4,
        align: isLeft ? 'left' : 'center',
        lineBreak: false,
        ellipsis: true,
      });
      x += w;
    });
    doc.y = y + ROW_HEIGHT;
    doc.moveTo(startX, doc.y).lineTo(tableRight, doc.y).stroke();
  };

  doc.lineWidth(0.5);
  doc.strokeColor(GRID_COLOR);

  const pageBottom = doc.page.height - doc.page.margins.bottom;
  // Vertical-rule segments: one per page the table spans. With one status
  // row per selected QC status per PO the grid regularly outgrows a single
  // page, so the table continues on a fresh page with a repeated header.
  const segments = [{ top: doc.y, bottom: null }];

  // Header row labels - reused verbatim when the table spills to a new page.
  const headers = ['PO', 'Status', ...sizeList, 'Total', 'Cumulative'];

  /** Start a new page (with a repeated header row) when out of space. */
  const ensureRowSpace = () => {
    if (doc.y + ROW_HEIGHT <= pageBottom) return;
    segments[segments.length - 1].bottom = doc.y;
    doc.addPage();
    drawTableRow(headers, { bold: true, fill: HEADER_BG, textColor: TEXT_WHITE });
    segments.push({ top: doc.y, bottom: null });
  };

  // Header row: dark fill + bold pure-white text.
  drawTableRow(headers, { bold: true, fill: HEADER_BG, textColor: TEXT_WHITE });

  // Status rows: one row per selected QC status under each PO, then the
  // PO's highlighted Sub Total row - the size quantities and total summed
  // across the block's status rows, with the PO's cumulative output on the
  // Cumulative column. Defensively filter out any status rows that contain
  // zero quantities or no data - only actively populated rows are rendered.
  blocks.forEach((block) => {
    block.statuses
      .filter((statusRow) =>
        Object.values(statusRow.sizes).some((qty) => qty !== 0)
      )
      .forEach((statusRow) => {
        ensureRowSpace();
        drawTableRow([
          block.po,
          statusRow.status,
          ...sizeList.map((s) => fmt(statusRow.sizes[s])),
          fmt(statusRow.total),
          '-',
        ]);
      });
    ensureRowSpace();
    drawTableRow(
      [
        block.po,
        'Sub Total',
        ...sizeList.map((s) => fmt(block.subTotal.sizes[s])),
        fmt(block.subTotal.total),
        fmt(block.cumulativeOutput),
      ],
      { bold: true, fill: SUBTOTAL_BG, textColor: TEXT_DARK }
    );
  });

  // Grand TOTAL footer row: dark fill + bold pure-white text. It sums the
  // PO Sub Totals (identical to the aggregate summary, since the block
  // status rows cover every scan - extras included).
  const summaryCells = [
    'TOTAL',
    '',
    ...sizeList.map((s) => fmt(summary.sizes[s])),
    fmt(summary.dailyTotal),
    fmt(summary.cumulativeOutput),
  ];
  ensureRowSpace();
  drawTableRow(summaryCells, { bold: true, fill: TOTAL_BG, textColor: TEXT_WHITE });

  // Close the last segment and draw the full grid: a top border per segment
  // + a vertical rule at every column boundary so rows and columns are
  // clearly separated on every page.
  segments[segments.length - 1].bottom = doc.y;
  segments.forEach((segment) => {
    doc.moveTo(tableLeft, segment.top).lineTo(tableRight, segment.top).stroke();
    colXs.forEach((x) => {
      doc.moveTo(x, segment.top).lineTo(x, segment.bottom).stroke();
    });
  });

  // Restore dark text so the signature/footer text below the table stays
  // visible (the TOTAL row's last text fill was white).
  doc.fillColor(TEXT_DARK);
  doc.moveDown(1);

  // ---- Signature section ----
  doc.fontSize(10).font('Helvetica');
  const sigY = doc.y;
  const sigWidth = 250;
  doc.text('Prepared By: ___________________', tableLeft, sigY);
  doc.text('Approved By: ___________________', tableLeft + sigWidth + 30, sigY);
  doc.moveDown(2);

  // ---- System footer ----
  doc.fontSize(8).font('Helvetica-Oblique').text(SYSTEM_FOOTER, { align: 'center' });
  doc.end();

  const awaitBuffer = () =>
    new Promise((resolve) => {
      if (doc._ended) return resolve(Buffer.concat(chunks));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

  const buffer = await awaitBuffer();
  const fileName = `Daily_Output_Report_${date || new Date().toISOString().slice(0, 10)}.pdf`;
  return { buffer, fileName };
}